export const cars = [
  "Acura Integra",
  "Audi A3",
  "Audi A4",
  "Audi A6",
  "BMW 3-Series",
  "BMW 5 Series",
  "BYD Seal",
  "Cadillac CT4",
  "Cadillac CT5",
  "Chevrolet Cruze",
  "Citroën C3",
  "Fiat 500",
  "Honda Accord",
  "Honda City",
  "Hyundai Accent",
  "Hyundai Elantra",
  "Hyundai Grand i10 Nios",
  "Hyundai i20",
  "Kia Cerato",
  "Maruti Suzuki Alto 800",
  "Maruti Suzuki Baleno",
  "Maruti Suzuki Dzire",
  "Maruti Suzuki Swift",
  "Maruti Suzuki Wagon R",
  "Mazda 3",
  "Mercedes-Benz C-Class",
  "Mercedes-Benz E-Class",
  "Nissan Altima",
  "Nissan Leaf",
  "Peugeot 208",
  "Renault Kwid",
  "Škoda Octavia",
  "Škoda Slavia",
  "Škoda Superb",
  "Subaru Impreza",
  "Suzuki Celerio",
  "Toyota Camry",
  "Toyota Corolla",
  "Volkswagen Golf",
  "Volkswagen Passat",
  "Volkswagen Polo",
  "Volvo S60",
  "Audi Q3",
  "Audi Q5",
  "Audi Q7",
  "BMW X1",
  "BMW X3",
  "Buick Enclave",
  "Chevrolet Equinox",
  "Citroën C5 Aircross",
  "Dacia Duster",
  "Ford EcoSport",
  "Ford Escape",
  "Ford Explorer",
  "Honda CR-V",
  "Honda Elevate",
  "Hyundai Creta",
  "Hyundai Tucson",
  "Hyundai Venue",
  "Jeep Compass",
  "Jeep Wrangler",
  "Kia Seltos",
  "Kia Sonet",
  "Kia Sportage",
  "Land Rover Discovery Sport",
  "Mahindra Scorpio-N",
  "Mahindra Thar",
  "Maruti Suzuki Fronx",
  "Maruti Suzuki Grand Vitara",
  "Maruti Suzuki Vitara Brezza",
  "Mazda CX-5",
  "Mercedes-Benz GLC",
  "Mitsubishi Outlander",
  "Nissan Rogue",
  "Renault Kiger",
  "Renault Triber",
  "Škoda Kodiaq",
  "Škoda Kushaq",
  "Subaru Forester",
  "Suzuki Jimny",
  "Tata Nexon",
  "Tata Punch",
  "Toyota RAV4",
  "Toyota Urban Cruiser Hyryder",
  "Volkswagen Taigun",
  "Volkswagen Tiguan",
  "Volvo XC40",
  "Chevrolet Silverado",
  "Dodge Caravan",
  "Ford F-Series",
  "Isuzu D-Max",
  "Kia Carens",
  "Mahindra Bolero",
  "Maruti Suzuki Ertiga",
  "Maruti Suzuki Eeco",
  "Toyota Hilux",
  "Toyota Innova Crysta",
  "Aston Martin Valkyrie",
  "Audi R8",
  "Bentley Continental GT",
  "Bugatti Chiron",
  "Ferrari 849 Testarossa",
  "Ford Mustang",
  "Jaguar F-Type",
  "Lamborghini Aventador",
  "Lucid Air",
  "McLaren Artura",
  "Mercedes-AMG SLC 43",
  "Porsche 911",
  "Rolls-Royce Phantom",
  "BYD Atto 3",
  "Hyundai Ioniq 5",
  "Kia EV6",
  "Polestar 2",
  "Rivian R1T",
  "Tata Nexon EV",
  "Tesla Model 3",
  "Tesla Model Y",
  "Volvo EX30"
]
